


apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: geoserver
  namespace: csvs
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/acme-challenge-type: dns01
    # appgw.ingress.kubernetes.io/hostname-extension : "staging.geoserver.csopenportal.co.uk"
spec:
  rules:
  - host: staging.geoserver.csopenportal.co.uk
    http:
      paths:
      - backend:
          service:
            name: geoserver
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - staging.geoserver.csopenportal.co.uk
    secretName: ssl-csopenportal-cert

    