{{ if .Values.ingress.enabled}}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{.Values.ingress.domain}}
  namespace: csvs
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    {{ if .Values.ingress.ssl.enabled }}
    cert-manager.io/cluster-issuer: {{.Values.ingress.ssl.clusterIssuerName}}
    cert-manager.io/acme-challenge-type: dns01
    {{end}}
spec:
  rules:
  - host: {{.Values.ingress.domain}}
    http:
      paths:
      - backend:
          service:
            name: geoserver
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  {{ if .Values.ingress.ssl.enabled }}
  tls:
  - hosts:
    - {{.Values.ingress.domain}}
    secretName: ssl-csopenportal-cert
  {{end}}


  {{ end }}