apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-geoserver-vector-data-storage-container
  annotations:
    pv.kubernetes.io/provisioned-by: "blob.csi.azure.com"
spec:
  capacity:
    storage: "1Pi"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - "-o allow_other"
    - "--file-cache-timeout-in-seconds=120"
  csi:
    driver: "blob.csi.azure.com"
    readOnly: true
    volumeHandle: "geoserver-vector-data-storage-container"
    volumeAttributes:
      containerName: "geoserver-vector-data"
    nodeStageSecretRef:
      name: "geoserver-storage-account-secret"
      namespace: "csvs"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-geoserver-rasters-data-storage-container
  annotations:
    pv.kubernetes.io/provisioned-by: "blob.csi.azure.com"
spec:
  capacity:
    storage: "1Pi"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - "-o allow_other"
    - "--file-cache-timeout-in-seconds=120"
  csi:
    driver: "blob.csi.azure.com"
    readOnly: true
    volumeHandle: "geoserver-rasters-data-storage-container"
    volumeAttributes:
      containerName: "geoserver-rasters-data"
    nodeStageSecretRef:
      name: "geoserver-storage-account-secret"
      namespace: "csvs"


