{{- if .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "geoserver.fullname" . }}-pod-reader
  namespace: {{ .Release.Namespace }}
  labels: {{- include "geoserver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "geoserver.fullname" . }}-pod-reader
  namespace: {{ .Release.Namespace }}
  labels: {{- include "geoserver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "geoserver.fullname" . }}-pod-reader
{{- end }}

