apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
  serviceName: "geoserver"
  template:
    metadata:
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      # - name: {{ .Chart.Name }}-sidecar
      #   image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
      #   imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
      #   volumeMounts:
      #     - mountPath: "/geoserver_data/data"
      #       name:  {{ .Values.pvc.remoteData.name }}
      #   {{- if .Values.pvc.rasters.enabled }}
      #     - mountPath: "/rasters_data"
      #       name: {{ .Values.pvc.rasters.name }}
      #   {{- end }}
      #   {{- if .Values.pvc.vectors.enabled }}
      #     - mountPath: "/vector_data"
      #       name: {{ .Values.pvc.vectors.name }}
      #   {{- end }}
      #   {{- if .Values.pvc.webinf.enabled }}
      #     - mountPath: "/usr/local/tomcat/webapps/geoserver/WEB-INF"
      #       name: {{ .Values.pvc.webinf.name }}
      #   {{- end }}
      #   env:
      #   - name: AWS_ACCESS_KEY_ID
      #     valueFrom:
      #       secretKeyRef:
      #         name: {{ include "geoserver.fullname" . }}
      #         key: aws-access-key-id
      #   - name: AWS_SECRET_ACCESS_KEY
      #     valueFrom:
      #       secretKeyRef:
      #         name: {{ include "geoserver.fullname" . }}
      #         key: aws-secret-access-key
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: "/geoserver_data/data"
            name:  {{ .Values.pvc.remoteData.name }}
          - mountPath: "/rasters_data"
            name: {{ .Values.pvc.rasters.name }}
          - mountPath: "/vector_data"
            name: {{ .Values.pvc.vectors.name }}
          - mountPath: "/usr/local/tomcat/webapps/geoserver/WEB-INF"
            name: {{ .Values.pvc.webinf.name }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.pvc.remoteData.name }}
      spec:
        storageClassName: {{ .Values.pvc.remoteData.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: {{ .Values.pvc.rasters.name }}
      spec:
        storageClassName: {{ .Values.pvc.remoteData.storageClassName | quote }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 80Gi
    - metadata:
        name: {{ .Values.pvc.vectors.name }}
      spec:
        storageClassName: {{ .Values.pvc.remoteData.storageClassName | quote }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: {{ .Values.pvc.webinf.name }}
      spec:
        storageClassName: {{ .Values.pvc.remoteData.storageClassName | quote }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

