kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  {{ .Values.pvc.webinf.storageClassName }}
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  {{ .Values.pvc.vectors.storageClassName }}
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS

---


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  {{ .Values.pvc.rasters.storageClassName }}
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS

---


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  {{ .Values.pvc.remoteData.storageClassName }}
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS