replicaCount: 1

image:
  repository: ivicamaticsd/csvs-geoserver
  tag: "latest"
  pullPolicy: Always

sidecar:
  image:
    repository: ivicamaticsd/csvs-geoserver-sidecar
    tag: "latest"
    pullPolicy: Always

pvc:
  webinf:
    name: geoserver-webinf
    storageClassName: geoserver-webinf-data-pvc-storage-class
  vectors:
    name: geoserver-vectors
    storageClassName: geoserver-vectors-data-pvc-storage-class
  rasters:
    name: geoserver-rasters
    storageClassName: geoserver-rasters-data-pvc-storage-class
  remoteData:
    name: geoserver-remote-data
    storageClassName: geoserver-remote-data-pvc-storage-class
  