apiVersion: v1
kind: Service
metadata:
  name: {{ include "terria.fullname" . }}
  labels:
    {{- include "terria.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverConfig.type }}
  ports:
    - port: {{ .Values.serverConfig.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "terria.selectorLabels" . | nindent 4 }}
