apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-thredds-storage-container
  annotations:
    pv.kubernetes.io/provisioned-by: "blob.csi.azure.com"
spec:
  capacity:
    storage: "1Pi"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - "-o allow_other"
    - "--file-cache-timeout-in-seconds=120"
  csi:
    driver: "blob.csi.azure.com"
    readOnly: true
    volumeHandle: "thredds-storage-container-handle"
    volumeAttributes:
      containerName: "thredds-storage-container"
    nodeStageSecretRef:
      name: "storage-account-secret"
      namespace: "csvs"


