apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-thredds-storage-container
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Pi"
  storageClassName: azureblob-fuse-premium
  volumeName: "pv-thredds-storage-container"
