apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
    {{- include "thredds.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "thredds.selectorLabels" . | nindent 6 }}
  serviceName: "thredds"
  volumeClaimTemplates:
          - metadata:
             name: {{ .Values.pvc.configuration.name }}
            spec:
              storageClassName: {{ .Values.pvc.configuration.storageClassName | quote }}
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
          
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "thredds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
     apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thredds.fullname" . }}
  labels:
    {{- include "thredds.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thredds.selectorLabels" . | nindent 6 }}
  serviceName: "thredds"
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.pvc.configuration.name }}
      spec:
        storageClassName: {{ .Values.pvc.configuration.storageClassName | quote }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "thredds.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: pvc-thredds-storage-container
      serviceAccountName: {{ include "thredds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-{{ .Chart.Name }}
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        imagePullPolicy: {{ .Values.initImage.pullPolicy }}
        volumeMounts:
        - name: {{ .Values.pvc.configuration.name }}
          mountPath: "/thredds-content"
        command: ["cp", "-r", "thredds", "thredds-content"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/data"
            name: storage-volume
          - mountPath: "/usr/local/tomcat/content"
            name:  {{ .Values.pvc.configuration.name }}
          ports:
            - name: liveness-port
              containerPort: {{ .Values.service.port }}
              hostPort: {{ .Values.service.port }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /thredds/catalog.html
              port: liveness-port
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /thredds/catalog.html
              port: liveness-port
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
